INSERT INTO sector (id, level, name, sorting) VALUES (1, 0, 'Manufacturing', 10);
INSERT INTO sector (id, level, name, sorting) VALUES (19, 1, 'Construction materials', 20);
INSERT INTO sector (id, level, name, sorting) VALUES (18, 1, 'Electronics and Optics', 30);
INSERT INTO sector (id, level, name, sorting) VALUES (6, 1, 'Food and Beverage', 40);
INSERT INTO sector (id, level, name, sorting) VALUES (342, 2, 'Bakery & confectionery products', 50);
INSERT INTO sector (id, level, name, sorting) VALUES (43, 2, 'Beverages', 60);
INSERT INTO sector (id, level, name, sorting) VALUES (42, 2, 'Fish & fish products ', 70);
INSERT INTO sector (id, level, name, sorting) VALUES (40, 2, 'Meat & meat products', 80);
INSERT INTO sector (id, level, name, sorting) VALUES (39, 2, 'Milk & dairy products ', 90);
INSERT INTO sector (id, level, name, sorting) VALUES (437, 2, 'Other', 100);
INSERT INTO sector (id, level, name, sorting) VALUES (378, 2, 'Sweets & snack food', 110);
INSERT INTO sector (id, level, name, sorting) VALUES (13, 1, 'Furniture', 120);
INSERT INTO sector (id, level, name, sorting) VALUES (389, 2, 'Bathroom/sauna ', 130);
INSERT INTO sector (id, level, name, sorting) VALUES (385, 2, 'Bedroom', 140);
INSERT INTO sector (id, level, name, sorting) VALUES (390, 2, 'Children’s room ', 150);
INSERT INTO sector (id, level, name, sorting) VALUES (98, 2, 'Kitchen ', 160);
INSERT INTO sector (id, level, name, sorting) VALUES (101, 2, 'Living room ', 170);
INSERT INTO sector (id, level, name, sorting) VALUES (392, 2, 'Office', 180);
INSERT INTO sector (id, level, name, sorting) VALUES (394, 2, 'Other (Furniture)', 190);
INSERT INTO sector (id, level, name, sorting) VALUES (341, 2, 'Outdoor ', 200);
INSERT INTO sector (id, level, name, sorting) VALUES (99, 2, 'Project furniture', 210);
INSERT INTO sector (id, level, name, sorting) VALUES (12, 1, 'Machinery', 220);
INSERT INTO sector (id, level, name, sorting) VALUES (94, 2, 'Machinery components', 230);
INSERT INTO sector (id, level, name, sorting) VALUES (91, 2, 'Machinery equipment/tools', 240);
INSERT INTO sector (id, level, name, sorting) VALUES (224, 2, 'Manufacture of machinery ', 250);
INSERT INTO sector (id, level, name, sorting) VALUES (97, 2, 'Maritime', 260);
INSERT INTO sector (id, level, name, sorting) VALUES (271, 3, 'Aluminium and steel workboats ', 270);
INSERT INTO sector (id, level, name, sorting) VALUES (269, 3, 'Boat/Yacht building', 280);
INSERT INTO sector (id, level, name, sorting) VALUES (230, 3, 'Ship repair and conversion', 290);
INSERT INTO sector (id, level, name, sorting) VALUES (93, 2, 'Metal structures', 300);
INSERT INTO sector (id, level, name, sorting) VALUES (508, 2, 'Other', 310);
INSERT INTO sector (id, level, name, sorting) VALUES (227, 2, 'Repair and maintenance service', 320);
INSERT INTO sector (id, level, name, sorting) VALUES (11, 1, 'Metalworking', 330);
INSERT INTO sector (id, level, name, sorting) VALUES (67, 2, 'Construction of metal structures', 340);
INSERT INTO sector (id, level, name, sorting) VALUES (263, 2, 'Houses and buildings', 350);
INSERT INTO sector (id, level, name, sorting) VALUES (267, 2, 'Metal products', 360);
INSERT INTO sector (id, level, name, sorting) VALUES (542, 2, 'Metal works', 370);
INSERT INTO sector (id, level, name, sorting) VALUES (75, 3, 'CNC-machining', 380);
INSERT INTO sector (id, level, name, sorting) VALUES (62, 3, 'Forgings, Fasteners ', 390);
INSERT INTO sector (id, level, name, sorting) VALUES (69, 3, 'Gas, Plasma, Laser cutting', 400);
INSERT INTO sector (id, level, name, sorting) VALUES (66, 3, 'MIG, TIG, Aluminum welding', 410);
INSERT INTO sector (id, level, name, sorting) VALUES (9, 1, 'Plastic and Rubber', 420);
INSERT INTO sector (id, level, name, sorting) VALUES (54, 2, 'Packaging', 430);
INSERT INTO sector (id, level, name, sorting) VALUES (556, 2, 'Plastic goods', 440);
INSERT INTO sector (id, level, name, sorting) VALUES (559, 2, 'Plastic processing technology', 450);
INSERT INTO sector (id, level, name, sorting) VALUES (55, 3, 'Blowing', 460);
INSERT INTO sector (id, level, name, sorting) VALUES (57, 3, 'Moulding', 470);
INSERT INTO sector (id, level, name, sorting) VALUES (53, 3, 'Plastics welding and processing', 480);
INSERT INTO sector (id, level, name, sorting) VALUES (560, 2, 'Plastic profiles', 490);
INSERT INTO sector (id, level, name, sorting) VALUES (5, 1, 'Printing ', 500);
INSERT INTO sector (id, level, name, sorting) VALUES (148, 2, 'Advertising', 510);
INSERT INTO sector (id, level, name, sorting) VALUES (150, 2, 'Book/Periodicals printing', 520);
INSERT INTO sector (id, level, name, sorting) VALUES (145, 2, 'Labelling and packaging printing', 530);
INSERT INTO sector (id, level, name, sorting) VALUES (7, 1, 'Textile and Clothing', 540);
INSERT INTO sector (id, level, name, sorting) VALUES (44, 2, 'Clothing', 550);
INSERT INTO sector (id, level, name, sorting) VALUES (45, 2, 'Textile', 560);
INSERT INTO sector (id, level, name, sorting) VALUES (8, 1, 'Wood', 570);
INSERT INTO sector (id, level, name, sorting) VALUES (337, 2, 'Other (Wood)', 580);
INSERT INTO sector (id, level, name, sorting) VALUES (51, 2, 'Wooden building materials', 590);
INSERT INTO sector (id, level, name, sorting) VALUES (47, 2, 'Wooden houses', 600);
INSERT INTO sector (id, level, name, sorting) VALUES (3, 0, 'Other', 610);
INSERT INTO sector (id, level, name, sorting) VALUES (37, 1, 'Creative industries', 620);
INSERT INTO sector (id, level, name, sorting) VALUES (29, 1, 'Energy technology', 630);
INSERT INTO sector (id, level, name, sorting) VALUES (33, 1, 'Environment', 640);
INSERT INTO sector (id, level, name, sorting) VALUES (2, 0, 'Service', 650);
INSERT INTO sector (id, level, name, sorting) VALUES (25, 1, 'Business services', 660);
INSERT INTO sector (id, level, name, sorting) VALUES (35, 1, 'Engineering', 670);
INSERT INTO sector (id, level, name, sorting) VALUES (28, 1, 'Information Technology and Telecommunications', 680);
INSERT INTO sector (id, level, name, sorting) VALUES (581, 2, 'Data processing, Web portals, E-marketing', 690);
INSERT INTO sector (id, level, name, sorting) VALUES (576, 2, 'Programming, Consultancy', 700);
INSERT INTO sector (id, level, name, sorting) VALUES (121, 2, 'Software, Hardware', 710);
INSERT INTO sector (id, level, name, sorting) VALUES (122, 2, 'Telecommunications', 720);
INSERT INTO sector (id, level, name, sorting) VALUES (22, 1, 'Tourism', 730);
INSERT INTO sector (id, level, name, sorting) VALUES (141, 1, 'Translation services', 740);
INSERT INTO sector (id, level, name, sorting) VALUES (21, 1, 'Transport and Logistics', 750);
INSERT INTO sector (id, level, name, sorting) VALUES (111, 2, 'Air', 760);
INSERT INTO sector (id, level, name, sorting) VALUES (114, 2, 'Rail', 770);
INSERT INTO sector (id, level, name, sorting) VALUES (112, 2, 'Road', 780);
INSERT INTO sector (id, level, name, sorting) VALUES (113, 2, 'Water', 790);